name: multi_imei
description: Get android IMEI list. Supports Android versions from M to P (inclusive)
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.artembark.multi_imei
        pluginClass: MultiImeiPlugin
